"""
models.py
Purpose: Defines the SQLAlchemy database models for storing captured packets
and security alerts triggered by the threat detection rules.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from database import Base

class PacketLog(Base):
    """
    Represents logged network packets captured by the sniffer.
    """
    __tablename__ = 'packet_logs'

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    source_ip = Column(String(50), nullable=True)
    destination_ip = Column(String(50), nullable=True)
    protocol = Column(String(20), nullable=True)
    length = Column(Integer)
    info = Column(Text, nullable=True)  # Scapy human-readable summary

    # Relationship to link packets to their triggered alerts
    alerts = relationship("AlertLog", back_populates="packet", cascade="all, delete-orphan")

class AlertLog(Base):
    """
    Represents security alerts generated by the Threat Detector when anomalies are detected.
    """
    __tablename__ = 'alert_logs'

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    rule_name = Column(String(100))
    severity = Column(String(20))  # Low, Medium, High
    description = Column(Text)
    packet_id = Column(Integer, ForeignKey('packet_logs.id', ondelete="CASCADE"), nullable=True)

    # Link back to the trigger packet details
    packet = relationship("PacketLog", back_populates="alerts")
